#!/bin/sh

sudo yum install -y docker zsh git
sudo service docker start
sudo usermod -a -G docker ec2-user
git clone https://github.com/sahsu/docker-munin-node.git
cd docker-munin-node
test -f /usr/local/bin/docker-compose
if [ $? -ne 0 ]; then
  curl -L https://github.com/docker/compose/releases/download/`curl https://github.com/docker/compose/releases | grep -A 5 Latest | tail -n 1 | awk '{print $2}' | sed -e 's;";;g' -e 's;href=/docker/compose/tree/;;g'`/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod 755 /usr/local/bin/docker-compose
fi
docker-compose up &
